### ISSUE TITLE
Impossible to receive a game invitation on android.

### ISSUE THREAD

**Issue by Xia0ben** [PhilippeVienne/RageGo-Core#5]
Here are the logs :
## Log from the android receiver, while the android emitter started the online game :

04-24 18:05:39.562    6819-6847/com.ragego.android I/GoGameScreen﹕ Assets loaded
04-24 18:05:39.582    6819-6847/com.ragego.android I/dalvikvm﹕ Could not find method javax.xml.bind.DatatypeConverter.printHexBinary, referenced from method com.ragego.engine.GameBoard.getBoardHash
04-24 18:05:39.582    6819-6847/com.ragego.android W/dalvikvm﹕ VFY: unable to resolve static method 16120: Ljavax/xml/bind/DatatypeConverter;.printHexBinary ([B)Ljava/lang/String;
04-24 18:05:39.582    6819-6847/com.ragego.android D/dalvikvm﹕ VFY: replacing opcode 0x71 at 0x0036
04-24 18:05:39.612    6819-6826/com.ragego.android I/dalvikvm﹕ Total arena pages for JIT: 11
04-24 18:05:46.262    6819-7320/com.ragego.android D/dalvikvm﹕ GC_FOR_ALLOC freed 6747K, 41% free 10448K/17496K, paused 194ms, total 211ms

---
## Log from the android receiver, while the desktop emitter started the online game :

04-24 18:12:32.262    9063-9090/com.ragego.android I/dalvikvm﹕ Could not find method javax.xml.bind.DatatypeConverter.printHexBinary, referenced from method com.ragego.engine.GameBoard.getBoardHash
04-24 18:12:32.262    9063-9090/com.ragego.android W/dalvikvm﹕ VFY: unable to resolve static method 16120: Ljavax/xml/bind/DatatypeConverter;.printHexBinary ([B)Ljava/lang/String;
04-24 18:12:32.262    9063-9090/com.ragego.android D/dalvikvm﹕ VFY: replacing opcode 0x71 at 0x0036
04-24 18:12:32.302    9063-9069/com.ragego.android I/dalvikvm﹕ Total arena pages for JIT: 11

---

**Comment by PhilippeVienne** [comment]
This bug is due that the xml DatatypeConverter is not in Dalvik machine.
