### ISSUE TITLE
Create a 9x9 map

### ISSUE THREAD

**Issue by PhilippeVienne** [PhilippeVienne/RageGo-Core#6]
This will be cool to have a pretty 9x9 map

**Comment by Xia0ben** [comment]
Scheduled for next week.

**Comment by PhilippeVienne** [comment]
So this week ?

**Comment by Xia0ben** [comment]
Actually, the one after ;-).
Thursday the 7th will be graphics day ! Expect reworked assets for the maps and the game menu, and maybe some wallpapers !
Even so, if you take a closer look on the last commit, you'll see a little surprise !

Thus I don't close the issue, even if a first version of the map, it is not its final form.

**Comment by Xia0ben** [comment]
DONE ! :D
