### ISSUE TITLE
HUD

### ISSUE THREAD

**Issue by PhilippeVienne** [PhilippeVienne/RageGo-Core#8]
It will be cool to have information in game and to be able to cancel a turn ...

**Comment by Xia0ben** [comment]
Assets done. Implementation should be done within the week.

**Comment by Xia0ben** [comment]
Implementation started

**Comment by PhilippeVienne** [comment]
HUD on Bottoms are too bigs and we can not play to the game, can you don't make them smaller or reduce them by touching escape key ?

**Comment by Xia0ben** [comment]
Assets size shall indeed be reworked through test with android devices. Meanwhile, a hiding button has been added and given how well it seems to be working, I shall consider your suggestion to keep it that way. ;-)

**Comment by Xia0ben** [comment]
HUD finished !
